alias: "Feed: Tech News"
description: "When new feed item is detected, send a notification"
trigger:
  platform: event
  event_type: feedreader
  event_data:
    feed_url: !secret rss_techfeed_url
action:
  - service: joaoapps_join.rafs_phone_send_tasker
    data:
      command: >-
        {{ 'newrss=:=' ~ trigger.event.data.id ~ '=:=' ~ trigger.event.data.title ~ '=:=' ~ trigger.event.data.link }}
