alias: "Location: Orion Lynn"
description: "When coordinates change, publish to Orion"
trigger:
  platform: state
  entity_id: person.lynn
condition:
  - condition: template
    value_template: >-
      {{ (trigger.from_state.attributes.latitude != trigger.to_state.attributes.latitude) or
      (trigger.from_state.attributes.longitude != trigger.to_state.attributes.longitude) }}
action:
  - service: rest_command.orion_publish_lynn
