alias: "Location: Owntracks Update Raf"
description: "When location changes, push to Owntracks"
trigger:
  platform: state
  entity_id: person.raf
condition:
  - condition: numeric_state
    entity_id: person.raf
    attribute: gps_accuracy
    above: 0
    below: 101
  - condition: template
    value_template: >-
      {{ (trigger.from_state.attributes.latitude != trigger.to_state.attributes.latitude) or
      (trigger.from_state.attributes.longitude != trigger.to_state.attributes.longitude) }}
action:
  - service: rest_command.owntracks_push_raf
