alias: "Location: Refresh Location Lynn"
description: "When disconnected from WiFi, request GPS update regularly"
trigger:
  - platform: time_pattern
    minutes: "/30"
condition:
  - not:
      - condition: state
        entity_id: device_tracker.lynns_iphone_wifi
        state: home
action:
  - service: script.update_location_lynn
