description: Sets the last run date
alias: RoboVac Last Run
trigger:
  platform: template
  value_template: "{% if is_state_attr('vacuum.robovac', 'status', 'cleaning')
    %}true{% endif %}"
  for:
    minutes: 30
action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.robovac_last_run
    data_template:
      date: "{{ states('sensor.date') }}"
