description: Sends a notification when Smoke detected
alias: Smoke Notification
trigger:
  platform: state
  entity_id: binary_sensor.smoke_sensor_smoke
  from: "off"
  to: "on"
action:
  - service: notify.telegram_raf
    data:
      message: Smoke Detected
