#!/bin/sh
set -e

# Add yamllint and prettier to PATH
NVM_BIN=$HOME/.nvm/versions/node/*/bin
NVM_BIN_PATH=$(echo $NVM_BIN)
PATH="${HOME}/.local/bin:${NVM_BIN_PATH}:${PATH}"

# Write json version file for README badge
HA_VER=$(cat .HA_VERSION)
echo "Setting HA version ${HA_VER}"
echo "{\"version\":\"${HA_VER}\"}" > .github/version.json
git add .github/version.json

if ! [ -x "$(command -v prettier)" ]; then
  echo 'Error: Prettier is not installed' && exit 1
else
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.md" "*.yml" "*.yaml" | sed 's| |\\ |g')
  if ! [ -z "$FILES" ]; then
    echo "Running Prettier..."

    # Prettify all selected files
    echo "$FILES" | xargs prettier --write

    # Add back the modified/prettified files to staging
    echo "$FILES" | xargs git add
  fi
fi

if ! [ -x "$(command -v yamllint)" ]; then
  echo 'Error: yamllint is not installed' && exit 1
else
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.yml" "*.yaml" | sed 's| |\\ |g')
  if ! [ -z "$FILES" ]; then
    echo "Running yamllint..."
    
    # Run yamllint
    echo "$FILES" | xargs yamllint
  fi
fi
