#!/bin/sh
set -e

if ! [ -x "$(command -v prettier)" ]; then
  echo 'Warning: Prettier is not installed' >&2
else
  # Get all staged files
  echo "Running Prettier..."
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.md" "*.yml" "*.yaml" | sed 's| |\\ |g')
  [ -z "$FILES" ] && exit 0

  # Prettify all selected files
  echo "$FILES" | xargs prettier --write

  # Add back the modified/prettified files to staging
  echo "$FILES" | xargs git add
fi

if ! [ -x "$(command -v yamllint)" ]; then
  echo 'Warning: yamllint is not installed' >&2
else
  # Run yamllint
  echo "Running yamllint..."
  yamllint .
fi
