alias: "Light: Guest Room Motion Off"
description: "When guest room has no motion, if lights are on, turn off"
trigger:
  platform: state
  entity_id: binary_sensor.guest_room_motion_sensor_occupancy
  from: "on"
  to: "off"
  for:
    minutes: 10
condition:
  - condition: state
    entity_id: light.guest_room
    state: "on"
action:
  - service: light.turn_off
    data:
      entity_id: light.guest_room
