alias: "Light: Guest Room No Motion"
description: "When guest room lights turn on, if there is no motion for 5 minutes before 5pm, turn off"
trigger:
  platform: state
  entity_id: light.guest_room
  from: "off"
  to: "on"
  for:
    minutes: 10
condition:
  - condition: state
    entity_id: binary_sensor.guest_room_motion_sensor_occupancy
    state: "off"
    for:
      minutes: 5
  - condition: time
    after: "06:00:00"
    before: "17:00:00"
action:
  - service: light.turn_off
    data:
      entity_id: light.guest_room
