alias: "Safety: Bathroom Humidity"
description: "When humidity is too high, send a notification"
trigger:
  platform: numeric_state
  entity_id:
    - sensor.bathroom_sensor_humidity
  above: 80
  for:
    minutes: 15
action:
  - service: notify.telegram_raf
    data:
      message: "High Humidity: {{ trigger.to_state.name }}"
