alias: "Safety: Shelly1 Alert"
description: "When something is wrong with the Shelly, send a notification"
trigger:
  - platform: state
    entity_id: binary_sensor.shelly1_overheating
    from: "off"
    to: "on"
  - platform: state
    entity_id: binary_sensor.shelly1_overpowering
    from: "off"
    to: "on"
  - platform: state
    entity_id: binary_sensor.shelly1_overvoltage
    from: "off"
    to: "on"
  - platform: numeric_state
    entity_id: sensor.shelly1_device_temperature
    above: 94
    for:
      minutes: 1
action:
  - service: notify.telegram_raf
    data:
      message: "Shelly1 Alert: {{ trigger.to_state.name }}: {{ trigger.to_state.state }}"
