alias: "Safety: Smoke"
description: "When smoke is detected, send a notification"
trigger:
  platform: state
  entity_id: binary_sensor.smoke_sensor_smoke
  from: "off"
  to: "on"
action:
  - service: notify.send_message
    data:
      entity_id: notify.telegram_raf
      message: "Alert: Smoke Detected"
