id: safety_water_leak
alias: 'Safety: Water Leak'
description: 'When water leak is detected, send a notification'
trigger:
  platform: state
  entity_id: 
    - binary_sensor.bathroom_water_sensor_water_leak
    - binary_sensor.boiler_water_sensor_water_leak
    - binary_sensor.kitchen_water_sensor_water_leak
  from: 'off'
  to: 'on'
action:
  - service: notify.telegram_raf
    data:
      message: >-
        "Water Leak: {{ trigger.to_state.name }}"
