alias: "Safety: Water Leak"
description: "When water leak is detected, send a notification"
trigger:
  platform: state
  entity_id:
    - binary_sensor.utility_room_moisture_water_leak
    - binary_sensor.kitchen_moisture_water_leak
  from: "off"
  to: "on"
action:
  - service: notify.send_message
    data:
      entity_id: notify.telegram_raf
      message: >-
        "Alert: Water Leak: {{ trigger.to_state.name }}"
