alias: "Alarm: Pre Morning Heating Living Room"
description: "At pre-alarm time, if cold, turn on the living room heater"
trigger:
  platform: time
  at: input_datetime.morning_alarm_pre
condition: "{{ (state_attr('climate.living_room_heater', 'current_temperature'))
  < (state_attr('climate.living_room_heater', 'temperature')) }}"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.living_room_heater
