alias: "Alarm: Pre Morning Heating Bedroom"
description: "At pre-alarm time, turn off bedroom heater"
trigger:
  platform: time
  at: input_datetime.morning_alarm_pre
condition:
  - condition: state
    entity_id: climate.bedroom_room_heater
    state: heat
action:
  - service: climate.turn_off
    data:
      entity_id: climate.bedroom_heater
