id: alarm_pre_morning_lights
alias: "Alarm: Pre Morning Lights"
description: "At pre-alarm time, turn on the lights"
trigger:
  platform: time
  at: input_datetime.morning_alarm_pre
action:
  - service: light.turn_on
    data:
      entity_id: light.bedside_lamp
      brightness_pct: 100
      transition: 1800
