########## Raf's Home Assistant Configuration ##########

########## How to organise configs ##########
# https://www.home-assistant.io/docs/configuration/splitting_configuration/
# https://www.home-assistant.io/docs/configuration/packages/
# https://www.home-assistant.io/docs/configuration/customizing-devices/

# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  name: Raf's Flat
  elevation: 10
  latitude: !secret home_lat
  longitude: !secret home_lon
  time_zone: Europe/London
  unit_system: metric
  currency: GBP
  country: GB
  external_url: !secret server_full_url
  internal_url: !secret server_full_url
  packages: !include_dir_named integrations
  customize: !include customizations/customizations.yaml
  customize_glob: !include customizations/glob_customizations.yaml
  allowlist_external_dirs:
    - !secret external_dir
  media_dirs:
    media: !secret media_dir
