alias: "Light: Living Room Sunset"
description: "At sunset, turn on living room evening scene"
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: "{{ states('input_number.sunset_elevation')|float }}"
  - platform: numeric_state
    entity_id: sensor.hue_motion_sensor_1_illuminance
    below: 400
    for:
      minutes: 10
condition:
  - condition: time
    after: "14:30:00"
  - condition: state
    entity_id: input_boolean.at_home
    state: "on"
  - condition: state
    entity_id: light.living_room
    state: "off"
  - condition: not
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: media_player.lg_tv
            state: "on"
          - condition: state
            entity_id: media_player.lg_tv
            attribute: source
            state:
              - Amazon Prime Video
              - Netflix
              - Disney+
action:
  - service: scene.turn_on
    data:
      transition: 300
      entity_id: >-
        {% if is_state('media_player.lg_tv', 'off') %}scene.living_room_evening
        {% else %}scene.living_room_evening_tv{% endif %}
