id: security_blink_disarmed
alias: 'Security: Blink Disarmed'
description: 'When Blink is disarmed, arm it after 5 minutes'
trigger:
  platform: state
  entity_id: alarm_control_panel.blink_rafs_flat
  to: 'disarmed'
  for:
    minutes: 5
action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.blink_rafs_flat
