alias: "Security: Door Open Long"
description: "When Front Door is open for too long, send a notification"
trigger:
  platform: state
  entity_id: binary_sensor.front_door_sensor_contact
  to: "on"
  for:
    minutes: 15
action:
  - service: notify.telegram_raf
    data:
      message: "Front Door has been open for 15+ minutes"
