alias: "Security: Door Open"
description: "When front door opens, if away, send notification"
trigger:
  platform: state
  entity_id: binary_sensor.front_door_lock_door
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: input_boolean.at_home
    state: "off"
action:
  - service: notify.send_message
    data:
      entity_id: notify.telegram_raf
      message: "Alert: Front door has been opened"
