alias: "Security: Door Open"
description: "When front door opens, if away, send notification"
trigger:
  platform: state
  entity_id: binary_sensor.front_door_sensor_contact
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: input_boolean.at_home
    state: "off"
  - condition: numeric_state
    entity_id: proximity.raf_home
    above: 1
  - condition: numeric_state
    entity_id: proximity.lynn_home
    above: 1
action:
  - service: notify.telegram_raf
    data:
      message: "Front door has been opened"
