alias: "Security: Home Disarm Blink"
description: "When door opens while home, disarm Blink for some time"
mode: restart
trigger:
  platform: state
  entity_id: binary_sensor.front_door_sensor_contact
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: person.raf
    state: "home"
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.blink_rafs_flat
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.front_door_sensor_contact
        to: "off"
        for:
          minutes: 5
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.blink_rafs_flat
