alias: "Security: Outdoor Motion"
description: "When motion outside, if away, send notification"
trigger:
  platform: state
  entity_id: binary_sensor.front_door_motion_sensor_occupancy
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: input_boolean.at_home
    state: "off"
action:
  - service: notify.telegram_raf
    data:
      message: "Motion detected outside"
