alias: "Presence: Away Update GPS Raf"
description: "When disconnected from WiFi, request GPS update"
trigger:
  platform: state
  entity_id: device_tracker.rafs_phone_wifi
  from: home
  for:
    minutes: 10
action:
  - service: script.update_location_raf
