alias: "Presence: Away Update Lynn GPS"
description: "When disconnected from WiFi, request GPS update"
trigger:
  platform: state
  entity_id: sensor.lynns_iphone_ssid
  from: !secret wifi_ssid
  for:
    minutes: 10
action:
  # https://companion.home-assistant.io/docs/notifications/notification-commands/#request-location-updates
  - service: notify.mobile_app_lynn_s_iphone
    data:
      message: "request_location_update"
