alias: "Presence: Away Update Raf GPS"
description: "When disconnected from WiFi, request GPS update"
trigger:
  platform: state
  entity_id: sensor.rafs_pixel_3a_wifi_connection
  from: !secret wifi_ssid
  for:
    minutes: 10
action:
  # https://companion.home-assistant.io/docs/notifications/notification-commands/#request-location-updates
  - service: notify.mobile_app_raf_s_pixel_3a
    data:
      message: "request_location_update"
