alias: "Presence: Away Set Away"
description: "When away for 5 minutes, set away"
trigger:
  platform: state
  entity_id: group.all_people
  from: home
  for:
    minutes: 5
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.at_home
