alias: "Presence: Away Update GPS Raf"
description: "When disconnected from WiFi, request GPS update"
trigger:
  platform: state
  entity_id: sensor.rafs_phone_wifi_connection
  from: !secret wifi_ssid
  for:
    minutes: 10
action:
  - service: script.update_location_raf
