alias: "Presence: Away Heating"
description: "When away, turn heating off"
trigger:
  platform: state
  entity_id: input_boolean.at_home
  from: "on"
  to: "off"
action:
  - service: climate.turn_off
    data:
      entity_id: all
