alias: "Presence: Away Update GPS Lynn"
description: "When disconnected from WiFi, request GPS update"
trigger:
  platform: state
  entity_id: device_tracker.lynns_iphone_wifi
  from: home
  for:
    minutes: 10
action:
  - service: script.update_location_lynn
