alias: "Presence: Away Update GPS Lynn"
description: "When disconnected from WiFi, request GPS update"
trigger:
  platform: state
  entity_id: sensor.lynns_iphone_ssid
  from: !secret wifi_ssid
  for:
    minutes: 10
action:
  - service: script.update_location_lynn
