alias: "Presence: Home Bedroom Heater"
description: "When home in the evening, if cold, turn heater on"
trigger:
  platform: state
  entity_id: input_boolean.at_home
  from: "off"
  to: "on"
condition:
  - condition: time
    after: "21:30:00"
    before: "05:30:00"
  - "{{ (state_attr('climate.bedroom_heater', 'current_temperature'))
    < (state_attr('climate.bedroom_heater', 'temperature')) }}"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.bedroom_heater
