alias: "Presence: Phone Home Check"
description: "When home, check phone GPS"
trigger:
  platform: state
  entity_id: input_boolean.at_home
  from: "off"
  to: "on"
condition:
  - condition: numeric_state
    entity_id: proximity.raf_home
    below: 2.5
action:
  - service: joaoapps_join.rafs_pixel_3a_send_tasker
    data:
      command: "check-home"
