alias: "Presence: Home WiFi Raf"
description: "When home, turn on WiFi"
trigger:
  - platform: state
    entity_id: person.raf
    to: "home"
  - platform: state
    entity_id: input_boolean.at_home
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: device_tracker.rafs_phone_wifi
    state: not_home
action:
  - service: joaoapps_join.rafs_phone_send_tasker
    data:
      command: "wifi-on"
