alias: "Presence: Home Update GPS Lynn"
description: "When potentially home, update GPS"
trigger:
  - platform: state
    entity_id: input_boolean.at_home
    from: "off"
    to: "on"
  - platform: state
    entity_id: binary_sensor.front_door_motion_sensor_occupancy
    from: "off"
    to: "on"
condition:
  - condition: numeric_state
    entity_id: automation.test_automation
    above: 15
    value_template: "{{ (now() - state.attributes.last_triggered) / timedelta(minutes=1) }}"
  - condition: numeric_state
    entity_id: proximity.lynn_home
    below: 10.0
  - not:
      - condition: state
        entity_id: person.lynn
        state: "home"
action:
  - service: script.update_location_lynn
