alias: "Presence: Home Bedroom Lights"
description: "When home in the evening, turn bedroom lights on"
trigger:
  platform: state
  entity_id: input_boolean.at_home
  from: "off"
  to: "on"
condition:
  - "{{ state_attr('sun.sun', 'elevation') <= states('input_number.sunset_elevation')|float }}"
action:
  - service: scene.turn_on
    data:
      entity_id: scene.bedroom_evening
