alias: "IR Command: LG TV Netflix Login"
description: "When IR Command received, if on Netflix, login"
trigger:
  platform: event
  event_type: esphome.ir_code_received
  event_data:
    device_name: "xiao-smart-ir-mate"
    protocol: nec
    address: "64260"
    command: "20145"
condition:
  - condition: state
    entity_id: media_player.lg_tv
    attribute: source
    state: Netflix
action:
  - delay:
      milliseconds: 100
  - service: webostv.button
    entity_id: media_player.lg_tv
    data:
      button: !secret netflix_pin_1
  - delay:
      milliseconds: 100
  - service: webostv.button
    entity_id: media_player.lg_tv
    data:
      button: !secret netflix_pin_2
  - delay:
      milliseconds: 100
  - service: webostv.button
    entity_id: media_player.lg_tv
    data:
      button: !secret netflix_pin_3
  - delay:
      milliseconds: 100
  - service: webostv.button
    entity_id: media_player.lg_tv
    data:
      button: !secret netflix_pin_4
