id: internet_down
alias: 'Internet: Down'
description: 'When internet is down, send a notification'
trigger:
  platform: state
  entity_id: binary_sensor.internet_connection
  from: "on"
  to: "off"
action:
  - service: persistent_notification.create
    data:
      title: Internet Down
      message: "{{ states('sensor.time') }}"
