id: internet_up
alias: 'Internet: Up'
description: 'When internet is up, send a notification'
trigger:
  platform: state
  entity_id: binary_sensor.internet_connection
  from: "off"
  to: "on"
action:
  - service: notify.telegram_raf
    data:
      message: Internet just turned back on
  - service: persistent_notification.create
    data:
      title: Internet Up
      message: "{{ states('sensor.time') }}"
