id: vacuum_finish_cleaning
alias: "Vacuum: Finish Cleaning"
description: "When Vacuum has been cleaning for long enough, dock it"
trigger:
  platform: numeric_state
  entity_id: sensor.robovac_runtime_today
  above: 1.00
condition:
  - "{{ trigger.from_state.state not in ['unknown', 'unavailable', 'none'] }}"
  - "{{ trigger.to_state.state not in ['unknown', 'unavailable', 'none'] }}"
  - "{{ trigger.from_state.state != trigger.to_state.state }}"
action:
  - service: vacuum.return_to_base
    entity_id: vacuum.robovac
