alias: "Vacuum: Home Schedule"
description: "At scheduled times, if not run today, start cleaning"
trigger:
  platform: time
  at: "18:15:00"
condition:
  - condition: time
    weekday:
      - mon
      # - tue
      - wed
      # - thu
      - fri
  - condition: numeric_state
    entity_id: sensor.robovac_last_run
    above: 0
action:
  - service: vacuum.start
    data:
      entity_id: vacuum.robovac
