id: vacuum_home_schedule
alias: "Vacuum: Home Schedule"
description: "At scheduled times, if home and not run today, start cleaning"
trigger:
  platform: time
  at: "17:15:00"
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - thu
      - fri
  - condition: state
    entity_id: input_boolean.at_home
    state: "on"
  - condition: numeric_state
    entity_id: sensor.robovac_last_run
    above: 0
action:
  - service: vacuum.start
    data:
      entity_id: vacuum.robovac
