alias: "Climate: Bedroom Heater Morning"
description: "At 6:00 AM, if sleeping and cold, turn on the bedroom heater"
trigger:
  platform: time
  at: "06:30:00"
condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: "on"
  - "{{ (state_attr('climate.bedroom_heater', 'current_temperature'))
    < (state_attr('climate.bedroom_heater', 'temperature')) }}"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.bedroom_heater
