alias: "Climate: Boiler Overnight"
description: "When scheduled, turn on the boiler overnight"
trigger:
  platform: time
  at: "05:00:00"
condition:
  - condition: state
    entity_id: input_boolean.sleeping
    state: "on"
  - or:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
      - condition: state
        entity_id: input_boolean.boiler_heat
        state: "on"
action:
  - service: switch.turn_on
    data:
      entity_id: switch.shelly1
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.boiler_heat
  - service: notify.telegram_raf
    data:
      message: "Boiler on, current energy: {{ states('sensor.shelly1_energy') }}"
