alias: "Climate: Evening Heating Bedroom"
description: "At 11:30 PM, if home and cold, turn on the bedroom heater"
trigger:
  platform: time
  at: "23:30:00"
condition:
  - condition: state
    entity_id: input_boolean.at_home
    state: "on"
  - "{{ (state_attr('climate.bedroom_heater', 'current_temperature'))
    < (state_attr('climate.bedroom_heater', 'temperature')) }}"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.bedroom_heater
