alias: "Climate: Living Room Open Window"
description: "When window is open, turn heater off"
trigger:
  platform: state
  entity_id: binary_sensor.living_room_window_sensor_contact
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: climate.living_room_heater
    state: heat
action:
  - service: climate.turn_off
    data:
      entity_id: climate.living_room_heater
