alias: "Reminder: Home Reconnect WiFi"
description: "When disconnected from WiFi, if home, send a notification"
trigger:
  platform: state
  entity_id: device_tracker.lynns_iphone_wifi
  to: not_home
  for:
    minutes: 30
condition:
  - condition: state
    entity_id: person.lynn
    state: home
    for:
      minutes: 30
action:
  - service: notify.mobile_app_lynn_s_iphone
    data:
      message: "Connect to WiFi you dummy"
