alias: "Media: Notification TV Clear"
description: "When TV is not playing, send clear command"
trigger:
  platform: state
  entity_id: media_player.lg_tv
  from: "on"
  to: "off"
condition:
  - condition: state
    entity_id: person.raf
    state: home
action:
  - service: joaoapps_join.rafs_phone_send_tasker
    data:
      command: "homemedia=:=clear=:=lg_tv"
