alias: "Media: Notification TV Clear"
description: "When TV is not playing, send clear command"
trigger:
  platform: state
  entity_id: media_player.lg_tv
  attribute: source
condition:
  - condition: state
    entity_id: person.raf
    state: home
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.lg_tv
        attribute: source
        state:
          - Amazon Prime Video
          - Disney+
          - Netflix
          - Plex
          - Photo & Video
action:
  - service: joaoapps_join.rafs_pixel_3a_send_tasker
    data:
      command: "homemedia=:=clear=:=lg_tv"
