alias: "Media: Notification TV Notify"
description: "When TV is playing, send notify command"
trigger:
  platform: state
  entity_id: media_player.lg_tv
  attribute: source
  for:
    seconds: 10
condition:
  - condition: state
    entity_id: person.raf
    state: home
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.lg_tv
        state: "off"
action:
  - service: joaoapps_join.rafs_phone_send_tasker
    data:
      command: "homemedia=:=tv=:=lg_tv"
