alias: "Media: Notification TV Notify"
description: "When TV is playing, send notify command"
trigger:
  platform: state
  entity_id: media_player.lg_tv
  attribute: source
condition:
  - condition: state
    entity_id: person.raf
    state: home
  - condition: state
    entity_id: media_player.lg_tv
    state: "on"
  - condition: state
    entity_id: media_player.lg_tv
    attribute: source
    state:
      - Amazon Prime Video
      - Apple TV+
      - BBC iPlayer
      - Chromecast
      - Disney+
      - Netflix
      - ITV Hub
      - NOW
      - PC
      - PS5
      - Photo & Video
      - Plex
      - Spotify - Music and Podcasts
      - Switch
      - Twitch
      - YouTube
action:
  - service: joaoapps_join.rafs_pixel_3a_send_tasker
    data:
      command: "homemedia=:=tv=:=lg_tv"
