description: Toggles Kitchen Lights
alias: Kitchen Switch
mode: single
trigger:
  - platform: state
    entity_id: sensor.kitchen_switch_action
    to: single_left
action:
  - service: light.toggle
    entity_id: light.kitchen
