# https://companion.home-assistant.io/docs/core/actions/
alias: "iOS Action: Light Bathroom"
description: "When iOS Action received, toggle Bathroom Lights"
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: light_bathroom
action:
  - service: light.toggle
    entity_id: light.bathroom
