# https://companion.home-assistant.io/docs/core/actions/
alias: "iOS Action: Light Bedroom Ceiling"
description: "When iOS Action received, toggle Bedroom Ceiling"
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: light_bedroom_ceiling
action:
  - service: light.toggle
    entity_id: light.bedroom_ceiling
