# https://companion.home-assistant.io/docs/core/actions/
alias: "iOS Action: Light Guest Room"
description: "When iOS Action received, toggle Guest Room Lights"
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: light_guest_room
action:
  - service: light.toggle
    entity_id: light.ceiling_4
