alias: "System: Certificate Expiry"
description: "When certificate is close to expiring, send a notification"
trigger:
  - platform: time
    at: "09:00:00"
condition: "{{ ((strptime(states('sensor.cert_expiry_home_assistant')
  | truncate(10, True, ''), '%Y-%m-%d').date()
  - strptime(states('sensor.date'), '%Y-%m-%d').date()).days)
  < 7 }}"
action:
  - service: notify.telegram_raf
    data:
      message: "Home Assistant Certificate Expiring On: {{ trigger.to_state.state }}"
