alias: "System: DuckDNS IP"
description: "When DuckDNS IP address changes, send a notification"
trigger:
  platform: state
  entity_id: sensor.duckdns_ip
conditions: "{{ trigger.to_state.state != Unknown }}"
action:
  - service: notify.telegram_raf
    data:
      message: "DuckDNS IP changed: {{ trigger.to_state.state }}"
