alias: "System: DuckDNS IP"
description: "When DuckDNS IP address changes, send a notification"
trigger:
  platform: state
  entity_id: sensor.duckdns_ip
condition:
  - "{{ trigger.to_state.state != 'Unknown' }}"
  - condition: state
    entity_id: binary_sensor.cloudflare
    state: "on"
    for:
      minutes: 10
action:
  - service: notify.telegram_raf
    data:
      message: "DuckDNS IP changed: {{ trigger.to_state.state }}"
