alias: "System: Update Available"
description: "When a new update is available, send a notification"
trigger:
  platform: state
  entity_id: update.home_assistant_core_update
  to: "on"
action:
  - service: notify.persistent_notification
    data:
      title: Update Available
