alias: "TV: LG TV On"
description: "When TV on command received, send WOL packet"
trigger:
  platform: webostv.turn_on
  entity_id: media_player.lg_tv
action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: !secret mac_lg_tv
