alias: "TV: Music Off"
description: "When TV turns on, if music is playing, turn it off"
trigger:
  platform: state
  entity_id: media_player.lg_tv
  from: "off"
  to: "on"
  for:
    seconds: 30
condition:
  - condition: state
    entity_id: media_player.speaker
    state: "playing"
action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.speaker
