alias: "TV: Off Scene"
description: "When TV turns off, if evening, activate evening scene"
trigger:
  platform: state
  entity_id: media_player.lg_tv
  to: "off"
  for:
    seconds: 15
condition:
  - "{{ state_attr('sun.sun', 'elevation') <= states('input_number.sunset_elevation')|float }}"
action:
  - service: scene.turn_on
    data:
      entity_id: scene.living_room_evening
