id: travel_absent_automations_state
alias: "Travel: Absent Automations State"
description: "When back home, set automations state"
trigger:
  platform: state
  entity_id: input_boolean.away
  from: "on"
  to: "off"
action:
  - service: automation.turn_on
    data:
      entity_id:
        - automation.vacuum_home_schedule
        - automation.vacuum_away_schedule
