alias: "Travel: Proximity Away Mode"
description: "When close to home, turn off away mode"
trigger:
  - platform: numeric_state
    entity_id: sensor.rafs_flat_raf_distance
    below: 2
  - platform: numeric_state
    entity_id: sensor.rafs_flat_lynn_distance
    below: 2
condition:
  - condition: state
    entity_id: input_boolean.away
    state: "on"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.away
