alias: "Travel: Tube Status"
description: "When the tube status changes, send a notification"
trigger:
  platform: state
  entity_id: sensor.elizabeth_line
  not_to:
    - "Good Service"
    - "Service Closed"
    - "unknown"
    - "unavailable"
action:
  - service: notify.mobile_app_rafs_phone
    data:
      title: "{{ trigger.to_state.name }}"
      message: "{{ trigger.to_state.state }}, {{ trigger.to_state.attributes.Description }}"
  - service: notify.mobile_app_lynns_phone
    data:
      title: "{{ trigger.to_state.name }}"
      message: "{{ trigger.to_state.state }}, {{ trigger.to_state.attributes.Description }}"
