alias: "Sleeping: Asleep Rain Warning"
description: "When asleep, if the window is open and rainy, warn"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.living_room_window_sensor_contact
    state: "on"
  - condition: state
    entity_id: weather.pirateweather
    state: rainy
action:
  - service: notify.mobile_app_rafs_phone
    data:
      title: "Rain warning"
      message: "May rain overnight, window is open"
