alias: "Sleeping: Asleep Media Volumes"
description: "When sleeping, set low volumes for media players"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "off"
  to: "on"
action:
  - service: media_player.volume_set
    data:
      entity_id:
        - media_player.bathroom_mini
        - media_player.guest_room_mini
        - media_player.speaker
        - media_player.living_room_display
      volume_level: 0.15
