alias: "Sleeping: Asleep Lights"
description: "When asleep, turn the lights off"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "off"
  to: "on"
action:
  - service: light.turn_off
    data:
      entity_id: light.bedroom
      transition: 15
  - delay:
      seconds: 15
  - service: light.turn_off
    data:
      entity_id: all
