alias: "Sleeping: Asleep Automations State"
description: "When asleep, set automations state"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "off"
  to: "on"
action:
  - service: automation.turn_on
    data:
      entity_id:
        - automation.alarm_pre_morning_heating_bedroom
        - automation.alarm_pre_morning_heating_living_room
        - automation.alarm_pre_morning_blanket
        - automation.alarm_pre_morning_lights
