alias: "Sleeping: Awake Lights"
description: "When awake, set the lights to the correct state"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "on"
  to: "off"
action:
  - service: switch.turn_off
    data:
      entity_id: switch.adaptive_lighting_sleep_mode_bathroom
  - service: light.turn_on
    data:
      entity_id: light.bedside_lamp
      brightness_pct: 100
      transition: 60
  - delay:
      hours: 1
  - service: light.turn_off
    data:
      entity_id: light.bedroom
