alias: "Sleeping: Awake Heating"
description: "When awake, turn the heating off"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "on"
  to: "off"
condition:
  - or:
      - condition: state
        entity_id: switch.plug5_power
        state: "on"
      - condition: state
        entity_id: input_boolean.electric_blanket_morning
        state: "on"
action:
  - service: switch.turn_off
    data:
      entity_id: switch.plug5_power
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.electric_blanket_morning
