alias: "Sleeping: Awake Bedroom Lights"
description: "When awake, turn the lights off after 30 minutes"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "on"
  to: "off"
action:
  - service: light.turn_on
    data:
      entity_id: light.bedside_lamp
      brightness_pct: 100
      transition: 60
  - delay:
      hours: 1
  - service: light.turn_off
    data:
      entity_id: light.bedroom
