alias: "Sleeping: Awake Automations State"
description: "When awake, set automations state"
trigger:
  platform: state
  entity_id: input_boolean.sleeping
  from: "on"
  to: "off"
action:
  - service: automation.turn_off
    data:
      entity_id:
        - automation.alarm_pre_morning_heating
        - automation.alarm_pre_morning_lights
