description: Makes a service call when a webhook is received from IFTTT with an event type of 'call_service'
alias: IFTTT
trigger:
  platform: event
  event_type: ifttt_webhook_received
  event_data:
    action: call_service
condition:
  condition: template
  value_template: '{{ trigger.event.type == "call_service" }}'
action:
  service_template: "{{ trigger.event.data.service }}"
  data_template:
    entity_id: "{{ trigger.event.data.entity_id }}"
