alias: "Test: Automation"
description: "When something, if another thing, do the thing"
trigger:
  platform: state
  entity_id: input_boolean.test_value
  from: "off"
  to: "on"
condition:
  - condition: numeric_state
    entity_id: automation.test_automation
    above: 10 # run this automation only if it has not run in the last 10 seconds
    # supports seconds, minutes, hours, use date() for days between dates
    value_template: "{{ (now() - state.attributes.last_triggered) / timedelta(seconds=1) }}"
    # value_template: "{{ (now().date() - state.attributes.last_triggered.date()).days }}"
action:
  - service: notify.persistent_notification
    data:
      # entity_id: entity.something
      message: "Test Automation"
      title: "Automation fired"
