id: log_level_system
alias: 'Log Level: System'
description: 'When the log level is set, changes the log level'
trigger:
  platform: state
  entity_id: input_select.log_level
action:
  service: logger.set_default_level
  data_template:
    level: "{{ states('input_select.log_level') }}"
