alias: "Log Level: Zigbee2Mqtt"
description: "When the log level is set, changes the log level"
trigger:
  platform: state
  entity_id: input_select.zigbee2mqtt_log_level
action:
  - service: mqtt.publish
    data:
      payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
      topic: zigbee2mqtt/bridge/config/log_level
