alias: "Keyboard Remote: Chromecast Play Pause Tab Casting"
description: "When play pause button pressed, casting tab, toggle playback"
trigger:
  platform: event
  event_type: keyboard_remote_command_received
  event_data:
    device_name: "flirc.tv flirc Keyboard"
    key_code: 164
condition:
  - condition: state
    entity_id: media_player.lg_tv
    attribute: source
    state: Chromecast
  - condition: state
    entity_id: media_player.living_room_tv
    attribute: media_title
    state: "Chrome tab casting"
action:
  - service: media_player.media_play_pause
    entity_id: media_player.lynns_pc
