alias: "Computer: Charger Off"
description: "When the laptop is on, turn on the charger"
trigger:
  platform: state
  entity_id: binary_sensor.lynns_pc_power
  from: "off"
  to: "on"
  for:
    minutes: 2
action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug5_power
