alias: "Computer: Charger Off"
description: "At night, turn off the charger"
trigger:
  platform: time
  at: "12:00:00"
action:
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.lynns_pc_power
        to: "off"
        for: 10
    timeout:
      hours: 3
    continue_on_timeout: false
  - service: switch.turn_off
    data:
      entity_id: switch.plug5_power
