id: computer_on
alias: "Computer: On"
description: "When the computer is on, turn on the Raspberry Pi"
trigger:
  platform: state
  entity_id: binary_sensor.rafs_pc_power
  from: "off"
  to: "on"
action:
  service: mqtt.publish
  data:
    topic: rafs-pi
    payload: "on"
