alias: "Computer: Pi On"
description: "When the computer is on, turn on the Raspberry Pi"
trigger:
  platform: state
  entity_id: binary_sensor.rafs_pc_power
  from: "off"
  to: "on"
  for:
    minutes: 2
action:
  - service: script.pi_on
