alias: "Computer: Pi Off"
description: "When the computer is off, turn off the Raspberry Pi"
trigger:
  platform: state
  entity_id: binary_sensor.rafs_pc_power
  from: "on"
  to: "off"
  for:
    minutes: 3
action:
  - service: script.pi_off
