alias: "Zone: Lynn Work"
description: "Send a notification when at work"
trigger:
  - platform: state
    entity_id: person.lynn
    to: "Lynn's Work"
    variables:
      message_verb: "arrived at"
  - platform: state
    entity_id: person.lynn
    from: "Lynn's Work"
    variables:
      message_verb: "left"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  - not:
      - condition: time
        after: "11:00:00"
        before: "15:00:00"
action:
  - service: notify.mobile_app_rafs_phone
    data:
      title: "Location Update"
      message: "Lynn has {{ message_verb }} the office"
