alias: "Zone: Lynn Home"
description: "Send a notification when at home"
trigger:
  platform: state
  entity_id: person.lynn
  to: "home"
condition:
  - not:
      - condition: state
        entity_id: person.raf
        state: "home"
  - condition: numeric_state
    entity_id: sensor.raf_lynn_distance
    above: 1
action:
  - service: notify.mobile_app_rafs_phone
    data:
      title: "Location Update"
      message: "Lynn has arrived at home"
