alias: "Zone: Raf Work"
description: "Send a notification when at work"
trigger:
  - platform: state
    entity_id: person.raf
    to: "Raf's Work"
    variables:
      message_verb: "arrived at"
  - platform: state
    entity_id: person.raf
    from: "Raf's Work"
    variables:
      message_verb: "left"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  - not:
      - condition: time
        after: "11:00:00"
        before: "15:00:00"
action:
  - service: notify.mobile_app_lynns_iphone
    data:
      title: "Location Update"
      message: "Raf has {{ message_verb }} the office"
