alias: "Zone: Raf Home"
description: "Send a notification when at home"
trigger:
  platform: state
  entity_id: person.raf
  to: "home"
  for:
    seconds: 10
condition:
  - not:
      - condition: state
        entity_id: person.lynn
        state: "home"
  - condition: numeric_state
    entity_id: sensor.raf_lynn_distance
    above: 1
action:
  - service: notify.mobile_app_lynns_iphone
    data:
      title: "Location Update"
      message: "Raf has arrived at home"
