alias: "Zone: Station"
description: "Send a notification when at station"
trigger:
  - platform: numeric_state
    entity_id: zone.station
    above: 0
    variables:
      notification_title: "Location Update"
      notification_message:
        "{{ state_attr(state_attr(trigger.entity_id, 'persons')[0],
        'friendly_name') }} is at the station"
condition:
  - or:
      - condition: state
        entity_id: device_tracker.rafs_phone_wifi
        state: not_home
        for:
          minutes: 30
      - condition: state
        entity_id: device_tracker.lynns_iphone_wifi
        state: not_home
        for:
          minutes: 30
action:
  - service: notify.mobile_app_rafs_phone
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
  - service: notify.mobile_app_lynns_iphone
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
