alias: "Switch: Hallway"
description: "When button pressed once, toggle lights"
trigger:
  - platform: state
    entity_id: sensor.hallway_switch_action
    to: single_left
  - platform: state
    entity_id: sensor.hallway_switch_action
    to: single_right
action:
  - service: light.toggle
    data:
      entity_id: light.hallway
      brightness_pct: 100
