alias: "Switch: Kitchen"
description: "When button pressed once, toggle lights"
trigger:
  - platform: state
    entity_id: sensor.kitchen_switch_action
    to: single_left
  - platform: state
    entity_id: sensor.kitchen_switch_action
    to: singe_right
action:
  - service: light.toggle
    entity_id: light.kitchen
