# https://templates.blakadder.com/slitinto_NX-SM110.html

substitutions:
  devicename: plug1
  upper_devicename: Plug1

esphome:
  name: ${devicename}
  comment: Slitinto NX-SM110
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret backup_wifi
      password: !secret backup_wifi_password
  ap:
    ssid: "esphome_${devicename}"
    password: !secret backup_wifi_password

captive_portal:

logger:
  level: WARN

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      inverted: True
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${upper_devicename} Power"
    id: relay
    pin: GPIO15
    on_turn_on:
      - switch.toggle: ledred
    on_turn_off:
      - switch.toggle: ledred
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: ledred
    pin: GPIO0
    inverted: True
    restore_mode: ALWAYS_OFF

sensor:
  - platform: wifi_signal
    name: "${upper_devicename} WiFi Signal"
    update_interval: 60s
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    power:
      name: "${upper_devicename} Wattage"
      unit_of_measurement: W
      id: wattage
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - 38 -> 6
            - 6275 -> 810
    current:
      name: "${upper_devicename} Amperage"
      unit_of_measurement: A
      id: current
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 5.46 -> 3.376
            - 0.077 -> 0.048
    voltage:
      name: "${upper_devicename} Voltage"
      unit_of_measurement: V
      id: voltage
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - 641 -> 244
            - 635 -> 243
    change_mode_every: 3
    update_interval: 12s
  - platform: total_daily_energy
    name: "${upper_devicename} Total Daily Energy"
    power_id: wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
