# https://templates.blakadder.com/hyleton_313.html

substitutions:
  devicename: plug3
  upper_devicename: Plug3

esphome:
  name: ${devicename}
  comment: Hyleton 313
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret backup_wifi
      password: !secret backup_wifi_password
  ap:
    ssid: "esphome_${devicename}"
    password: !secret backup_wifi_password

captive_portal:

logger:
  level: WARN

api:

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: "${upper_devicename} WiFi Signal"

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${upper_devicename} Power"
    id: relay
    pin: GPIO15
    on_turn_on:
      - switch.toggle: ledblue
      - switch.toggle: ledred
    on_turn_off:
      - switch.toggle: ledblue
      - switch.toggle: ledred
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: ledred
    pin: GPIO0
    inverted: True
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: ledblue
    pin: GPIO2
    inverted: True
    restore_mode: ALWAYS_OFF
