# https://templates.blakadder.com/gosund_UP111.html

substitutions:
  devicename: plug6
  upper_devicename: Plug6

esphome:
  name: ${devicename}
  comment: Gosund UP111
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret backup_wifi
      password: !secret backup_wifi_password
  ap:
    ssid: "esphome_${devicename}"
    password: !secret backup_wifi_password

captive_portal:

logger:
  level: WARN

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO3
      inverted: False
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${upper_devicename} Power"
    id: relay
    pin: GPIO14
    on_turn_on:
      - switch.toggle: ledblue
    on_turn_off:
      - switch.toggle: ledblue
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: ledblue
    pin: GPIO1
    inverted: False
    restore_mode: ALWAYS_OFF

sensor:
  - platform: wifi_signal
    name: "${upper_devicename} WiFi Signal"
    update_interval: 60s
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO5
    power:
      name: "${upper_devicename} Wattage"
      unit_of_measurement: W
      id: wattage
      accuracy_decimals: 0
      filters:
        - calibrate_linear: # Map sensor -> true value
            - 137.91483 -> 22.5
            - 199.97650 -> 32.8
            - 12981.23242 -> 2222
            - 13378 -> 2294
        - lambda: if (x < 1) return 0; else return x;
    current:
      name: "${upper_devicename} Amperage"
      unit_of_measurement: A
      id: current
      accuracy_decimals: 1
      filters:
        - calibrate_linear: # Map sensor -> true value
            - 0.14484 -> 0.156
            - 0.24141 -> 0.239
            - 11.13375 -> 9.24
    voltage:
      name: "${upper_devicename} Voltage"
      unit_of_measurement: V
      id: voltage
      accuracy_decimals: 0
      filters:
        - calibrate_linear: # Map sensor -> true value
            - 616.36011 -> 243.5
            - 606.68903 -> 240.1
    change_mode_every: 3
    update_interval: 3s
  - platform: total_daily_energy
    name: "${upper_devicename} Total Daily Energy"
    power_id: wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
