name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
  # schedule:
  #   - cron: 0 6 * * 6

jobs:
  yamllint:
    name: "Yaml Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Getting repo from GitHub
        uses: actions/checkout@v2

      - name: Running Yaml Lint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .

  config_check:
    name: "Config Check"
    runs-on: ubuntu-latest
    needs: [yamllint]
    steps:
      - name: Getting repo from GitHub
        uses: actions/checkout@v2

      - name: Setting up test environment
        run: |
          .github/setup.sh

      - name: Getting Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --version

      - name: Checking Home Assistant Configuration
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./ --script check_config --info all
